vich_uploader:
    db_driver: orm

    mappings:
       upload_video:
           uri_prefix: '%upload_video%'
           upload_destination: '%kernel.project_dir%/public/assets/videos'
           namer: 
            service: Vich\UploaderBundle\Naming\PropertyNamer
            options: { property : 'slug' }
